sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  global:
    - NUMPY_VERSION=1.10
    - SCIPY_VERSION=0.16
    #- INSTALL_OPTIONAL=true

#matrix:
  #include:
    #- python: 2.7
      #env: NUMPY_VERSION=1.8
    #- python: 3.4
      #env: NUMPY_VERSION=1.8

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib six pytest pip cython pandas
  - source activate testenv

  # Optional dependencies
  #- if $INSTALL_OPTIONAL; then conda install --yes pandas=0.14; fi

script:
  - python setup.py test
  - python setup.py install
